# Generated by Django 4.2.4 on 2023-08-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_user_userdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconditionlog",
            name="check_in_condition",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="deviceconditionlog",
            name="check_out_condition",
            field=models.CharField(max_length=100),
        ),
    ]
